# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-29 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0004_keyword_filter_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='filter_end_date',
        ),
    ]
