# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-31 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0003_remove_user_query_data'),
        ('filter', '0009_keyword_user_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='user_filter',
        ),
        migrations.AddField(
            model_name='keyword',
            name='users_with_this_filter',
            field=models.ManyToManyField(related_name='filter_user_used', to='login_reg.User'),
        ),
    ]
