# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-31 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0011_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='filter_end_date',
        ),
    ]
