# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-31 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0012_remove_keyword_filter_end_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='End_Time',
            new_name='Time',
        ),
    ]
