# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-31 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0013_auto_20190531_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='keyword_associated_with_time',
        ),
        migrations.RemoveField(
            model_name='time',
            name='user_associated_with_time',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='users_with_this_filter',
        ),
        migrations.AddField(
            model_name='keyword',
            name='filter_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
